### PR TITLE
add B44A test images

### PR DESCRIPTION
**Pull request by Narann**
This PR add two new images exported from Nuke:

crow_uncompressed.exr -> open in nuke -> write crow_b44a.exr (with B44A compression)
crow_b44a.exr -> open in nuke -> write crow_b44a_uncompressed.exr (without compression)

This will help to compare expected B44A output to our implementation.

### CODE REVIEW

**Comment by johannesvollmer** [comment]
Hey, did you accidentally mix up the directories? We have been working in the images/valid/custom/compression_methods/ folder last time, not custom/crowskull/ (they are actually different images). But don't worry! I'm already in the middle of implementing the tests and I have converted some images already.

**Comment by Narann** [comment]
You’re right, sorry.

If you already have those images, could you push them in dev? I would really want to have those images so I can finish the unit tests. :)

**Comment by johannesvollmer** [comment]
Yes, pushed that. Sorry for not communicating about my efforts to implement the tests myself earlier :) Let's see if the tests pass on your other PR and see if we can finally merge

**Comment by Narann** [comment]
Nice, thanks!

**Comment by Narann** [comment]
> Sorry for not communicating about my efforts to implement the tests myself earlier :)

It's OK, thanks for the hard work!

**Pull request closed without merging**
