### PR TITLE
Add PIZ compression! Yay!

### PR DESCRIPTION
**Pull request by johannesvollmer**
Thanks a ton to @dgsantana for the great work! It is a pleasure to work with you.

### CODE REVIEW

**Comment by johannesvollmer** [comment]
@dgsantana If you find the time to have a quick look, I'd like to release the next version at this point. The "rustification" of the piz module can be published as a non-breaking change.

**Comment by dgsantana** [comment]
Will look during tomorrow.

**Comment by johannesvollmer** [comment]
Thanks for checking!

**Comment by johannesvollmer** [comment]
Found a tiny little issue, and fixed it.. what could possibly go wrong

**Comment by johannesvollmer** [comment]
> johannesvollmer dismissed dgsantana’s stale review via 1a4869d 1 minute ago

Oh wow that sounds pretty rude actually :D

**Comment by johannesvollmer** [comment]
Tests pass so it can't be too bad. Merging now.

**Pull request merged**
