### PR TITLE
Project structure

### PR DESCRIPTION
**Pull request by johannesvollmer**
add git LFS attributes

### CODE REVIEW

**Comment by johannesvollmer** [comment]
This github pipeline apparently does not use git LFS. Can we make it use LFS?

**Comment by johannesvollmer** [comment]
Ok nice, the workflow works again, I guess

**Comment by johannesvollmer** [comment]
@virtualritz  I have got very bad news for this pull request

https://github.com/johannesvollmer/exrs/pull/88/checks?check_run_id=912058241

```
  batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
  batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
  batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
  ##[error]error: failed to fetch some objects from 'https://github.com/johannesvollmer/exrs.git/info/lfs'
  The process '/usr/bin/git' failed with exit code 2
```

**Comment by johannesvollmer** [comment]
As I am not willing to pay money for this project, the remaining options are:
- drop this pull request and change nothing
- drop github workflows, disabling automatic error checks 
- drop git LFS
    - use a git submodule for those files instead?  
      this should have the same effect, if I am not mistaken: for a normal clone, the image data is not downloaded, they have to be pulled separately

**Comment by virtualritz** [comment]
That's ridiculous. So you get punished for using LFS (which actually treats binary data more efficient than Git) but hosting the data in a plain Git repo is OK? Wtf?!

**Comment by virtualritz** [comment]
I didn't know this. I am thinking about tweeting my above reply to Github publicly and see what they reply.

**Comment by virtualritz** [comment]
From what I understand the 1GB quota is per user/month. So someone else would not see this message if they were also someone with permissions to merge the PR. And possibly you won't see it if you just wait with merging the pull request until 1. of August.
Just a guess from what I read about this quota so far in the last 5mins.

**Comment by johannesvollmer** [comment]
Nice logic, github

**Comment by johannesvollmer** [comment]
From what I have read, the qouta is measured for all downloads of the repo, which apparently includes the github workflow that checks pull requests

**Comment by johannesvollmer** [comment]
Anyways, 1GB per month is kind of demotivating and does not encourage contributions, so I think this is not really an option

**Comment by johannesvollmer** [comment]
I chose this PR, leaving the issue open to discussion

**Pull request closed without merging**
