### PR TITLE
Huffman compression part

### PR DESCRIPTION
**Pull request by dgsantana**
This contains the working compression part of the code. Haven't touch yet on the decompression.

### CODE REVIEW

**Comment by johannesvollmer** [comment]
Thanks for this update, I'll try to actually write PIZ images using this

**Comment by johannesvollmer** [comment]
The test did not pass on my system, might this be a different version than what you got on your computer?

**Comment by dgsantana** [comment]
> 
> 
> The test did not pass on my system. Might this be a different version than what you got on your computer?

That is the bug I detected probably. I'm trying to see what long code is wrong, already have a reproducible case.

**Comment by johannesvollmer** [comment]
Okidoki

**Pull request merged**
